# Generated by Django 3.2.4 on 2021-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_years', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='guess_day',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guess_month',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='guess',
            name='guess_year',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
