# Generated by Django 3.2.4 on 2021-06-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_years', '0002_auto_20210612_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guess',
            name='isGuessCorrect',
            field=models.BooleanField(null=True),
        ),
    ]
